------------------- QA (.100)

create sequence PSWEBLOG.SEQ_PEDIDOS_GUIAS_API minvalue 1 maxvalue 999999999999 start with 1 increment by 1 nocache;

create table PSWEBLOG.PEDIDOS_GUIAS_API
(
	ID_N NUMBER(35),
	PT_NUM_N NUMBER(35),
	TI_CVE_N NUMBER(35),
	GUIA_STR VARCHAR2(200),
	ID_PAQ_N NUMBER(5),
	STATUS_STR VARCHAR2(2),
	ORIGEN_STR VARCHAR2(2),
	FMOD_DT DATE,
	FALTA_DT TIMESTAMP
)
/

comment on table PSWEBLOG.PEDIDOS_GUIAS_API is 'TABLA PARA REGISTRO DE GUIAS DE PEDIDOS'
/

create unique index PSWEBLOG.PEDIDOS_GUIAS_API_ID_N_UINDEX
	on PSWEBLOG.PEDIDOS_GUIAS_API (ID_N)
/

alter table PSWEBLOG.PEDIDOS_GUIAS_API
	add REENVIO NUMBER(1) default 0
/




GRANT SELECT ON PSWEBLOG.SEQ_PEDIDOS_GUIAS_API TO PPVMX;
GRANT SELECT,INSERT , DELETE ON PSWEBLOG.PEDIDOS_GUIAS_API TO PPVMX;

---------------------- PRODUCCION
create sequence PSIWEB.SEQ_PEDIDOS_GUIAS_API minvalue 1 maxvalue 999999999999 start with 1 increment by 1 nocache;

create table PSIWEB.PEDIDOS_GUIAS_API
(
	ID_N NUMBER(35),
	PT_NUM_N NUMBER(35),
	TI_CVE_N NUMBER(35),
	GUIA_STR VARCHAR2(200),
	ID_PAQ_N NUMBER(5),
	STATUS_STR VARCHAR2(2),
	ORIGEN_STR VARCHAR2(2),
	FMOD_DT DATE,
	FALTA_DT TIMESTAMP,
    REENVIO NUMBER(1) default 0
);



GRANT SELECT ON PSIWEB.SEQ_PEDIDOS_GUIAS_API TO PPVMX;
GRANT SELECT,INSERT , DELETE ON PSIWEB.PEDIDOS_GUIAS_API TO PPVMX;

  --REGISTRO DE PICKING PACKING DE PEDIDOS MAGENTO. SOLO SE REGISTRAN AQUELLOS PEDIDOS QUE HAN SIDO PAGADOS
  IF(:NEW.PT_TIP_STR = 'M') THEN
  	IF((INSERTING AND :NEW.PT_ONLINE_N = 1) OR (UPDATING AND (:OLD.PT_ONLINE_N = 0 AND :NEW.PT_ONLINE_N = 1)) ) THEN
        	-- INSERCION PICKING-PACKING
        	INSERT INTO PSWEBLOG.CARGAMOS_PICKING_PACKING (CPP_ID_N, PT_NUM_N, TI_CVE_N, SO_ID_STR, CPP_ORIGEN_STR, CPP_FALTA_DT)
        	VALUES (PSWEBLOG.CPP_SEQUENCE.nextval,:NEW.PT_NUM_N,:NEW.TI_CVE_N,:NEW.SO_ID_STR,:NEW.PT_TIP_STR, SYSDATE);
    END IF;
    IF(:NEW.PT_TIP_STR = 'M' AND :NEW.PT_EST_STR = 'V' AND :NEW.TI_CVE_N = 29) THEN
            INSERT INTO PSIWEB.PEDIDOS_GUIAS_API (id_n,pt_num_n,ti_cve_n,status_str,origen_str,falta_dt)
            VALUES (PSIWEB.SEQ_PEDIDOS_GUIAS_API.nextval,:NEW.PT_NUM_N,:NEW.TI_CVE_N,'P','M',sysdate);
  	END IF;
  END IF;