------------------- QA (.100)

create sequence PSWEBLOG.SEQ_PEDIDOS_GUIAS_API minvalue 1 maxvalue 999999999999 start with 1 increment by 1 nocache;

create table PSWEBLOG.PEDIDOS_GUIAS_API
(
	ID_N NUMBER(35),
	PT_NUM_N NUMBER(35),
	TI_CVE_N NUMBER(35),
	GUIA_STR VARCHAR2(200),
	ID_PAQ_N NUMBER(5),
	STATUS_STR VARCHAR2(2),
	ORIGEN_STR VARCHAR2(2),
	FMOD_DT DATE,
	FALTA_DT TIMESTAMP
)
/

comment on table PSWEBLOG.PEDIDOS_GUIAS_API is 'TABLA PARA REGISTRO DE GUIAS DE PEDIDOS'
/

create unique index PSWEBLOG.PEDIDOS_GUIAS_API_ID_N_UINDEX
	on PSWEBLOG.PEDIDOS_GUIAS_API (ID_N)
/

alter table PSWEBLOG.PEDIDOS_GUIAS_API
	add REENVIO NUMBER(1) default 0
/




GRANT SELECT ON PSWEBLOG.SEQ_PEDIDOS_GUIAS_API TO PPVMX;
GRANT SELECT,INSERT , DELETE ON PSWEBLOG.PEDIDOS_GUIAS_API TO PPVMX;


